"""init

Revision ID: 3a31b8eb1bcf
Revises: 
Create Date: 2026-07-31 08:41:01.980735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a31b8eb1bcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название переговорной комнаты'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание комнаты'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='Вместимость комнаты (максимальное количество человек)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг доступности комнаты для бронирования'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID записи (автоинкремент)'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата/время добавления записи в таблицу'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата/время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    comment='Переговорные комнаты'
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='Уникальное имя пользователя для входа'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email пользователя'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Хешированный пароль (bcrypt)'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='Полное имя пользователя'),
    sa.Column('role', sa.Enum('employee', 'admin', name='booking_status_enum'), nullable=False, comment='Роль пользователя в системе'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг активности аккаунта'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID записи (автоинкремент)'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата/время добавления записи в таблицу'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата/время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    comment='Пользователи сервиса'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('time_slots',
    sa.Column('room_id', sa.Integer(), nullable=False, comment='ID комнаты'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Время начала слота'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Время окончания слота'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг доступности слота для бронирования'),
    sa.Column('day_of_week', sa.Integer(), nullable=True, comment='День недели (0=понедельник), если слот повторяется не каждый день'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID записи (автоинкремент)'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата/время добавления записи в таблицу'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата/время последнего обновления записи'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'start_time', 'end_time', name='uq_room_time_slot'),
    comment='Временные слоты переговорных комнат'
    )
    op.create_index(op.f('ix_time_slots_id'), 'time_slots', ['id'], unique=False)
    op.create_index(op.f('ix_time_slots_room_id'), 'time_slots', ['room_id'], unique=False)
    op.create_table('bookings',
    sa.Column('room_id', sa.Integer(), nullable=False, comment='ID комнаты'),
    sa.Column('time_slot_id', sa.Integer(), nullable=False, comment='ID временного слота'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя, создавшего бронирование'),
    sa.Column('booking_date', sa.Date(), nullable=False, comment='Дата бронирования'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание встречи/бронирования'),
    sa.Column('status', sa.String(), nullable=False, comment='Статус бронирования'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время отмены бронирования'),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True, comment='ID пользователя, отменившего бронирование'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID записи (автоинкремент)'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата/время добавления записи в таблицу'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата/время последнего обновления записи'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Переговорные комнаты'
    )
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_bookings_cancelled_by_id'), 'bookings', ['cancelled_by_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_time_slot_id'), 'bookings', ['time_slot_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_time_slot_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_cancelled_by_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_time_slots_room_id'), table_name='time_slots')
    op.drop_index(op.f('ix_time_slots_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
